spring.config.import=optional:file:.env[.properties]

#APP
server.port=8080
spring.application.name=base

#DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hit_springboot_2026_lesson_7?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


#JPA / HIBERNATE
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#JWT
jwt.secret=${JWT_SECRET}
#Expiration time (milliseconds)
#1 hour
jwt.access.expiration_time=${JWT_ACCESS_EXPIRATION_TIME}
#3 days
jwt.refresh.expiration_time=${JWT_REFRESH_EXPIRATION_TIME}

#Swagger
springdoc.api-docs.enabled=true
springdoc.packagesToScan=com.example.base.controller
springdoc.pathsToMatch=/**

#Info Admin
app.admin.username=admin@123
app.admin.email=admin@base.com
app.admin.password=${ADMIN_PASSWORD}
app.admin.firstName=System
app.admin.lastName=Administrator

#Security Endpoint
# Ở đây, chúng ta định nghĩa các endpoint cho từng loại người dùng. Các endpoint này sẽ được sử dụng trong lớp SecurityConfig để cấu hình quyền truy cập.
security.public-endpoints = api/v1/auth/**,/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html
security.user-endpoints = api/v1/user/**,/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html
security.admin-endpoints = api/v1/admin/**,/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html
security.swagger-endpoints=/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html

# Debug logging
#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.springframework.web.client=DEBUG
#logging.level.org.springframework.security.web=DEBUG