server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/conflict}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Allow automatic updates in local development
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:lminhhieu2507@gmail.com}
    password: ${MAIL_PASSWORD:bgcpomzycvqgzdtm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  flyway:
    enabled: true
    baseline-on-migrate: true

conflict:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970} # Default secret for local dev
    access-token-expiration: 86400000 # 24h
    refresh-token-expiration: 2592000000 # 30 days

logging:
  level:
    com.hit.conflict: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
